# Generated by Django 3.1 on 2020-09-07 12:59

from django.db import migrations, models
import utilities.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200907_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.utils.get_image_path),
        ),
    ]
