# Generated by Django 3.1 on 2020-08-28 13:22

from django.db import migrations, models
import utilities.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200828_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.utils.get_image_path),
        ),
    ]
