# Generated by Django 3.1 on 2020-09-04 10:41

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200903_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
