# Generated by Django 3.1 on 2020-09-07 13:03

from django.db import migrations, models
import utilities.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200907_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.utils.image_path),
        ),
    ]
